### ISSUE TITLE
Improvement to color

### ISSUE THREAD

**Issue by BrainMaestro** [sonmezonur/initials.rs#1]
Hi, this is a pretty cool library with some nice code. I took a look and I can see some improvements that can be made to how the color is stored in the `Avatar` struct. Like using `u8` instead of `i64`, and avoiding `Vec`. Would you be interested in a PR?

**Comment by sonmezonur** [comment]
Hi @BrainMaestro,

I appreciate your intention to contribute **initials** and happy to see your PR! I am also trying to improve the library and make it more stable. 

Thanks. Waiting for your PR.
